"""
Full AgentInko pipeline, end-to-end and in-sandbox (mock models + mock Godot):

  idea (Claude) -> storyboard spec (Claude) -> build (Kimi via MCP)
  -> Tier 1 build verify -> Tier 2 playtest -> ledger credit -> earned budget
  -> model-inference cost charged as a capped spend.

Run:  python3 pipeline_demo.py
"""

from model_gateway import ModelGateway, ModelSpec
from godot_mcp_client import GodotMCPClient
from mock_godot_mcp import MockGodotMCP
from skills import GameDevSkills, Storyboard
from playtest_agent import PlaytestAgent
from godot_verifier import evaluate_output
from incentive_framework import (
    AuditLog, OutcomeVerifier, IncentiveLedger, Treasury, TreasuryConfig,
    BudgetPolicy, KillSwitch, IncentiveHarness,
)

PROJECT = "res://inko_coin_dash"


# --- a fake model backend so the demo runs without API keys ---------------- #
def fake_invoke(spec: ModelSpec, prompt: str):
    """Return canned text + token counts per model. Real wiring replaces this."""
    if "JSON game spec" in prompt:
        text = (
            '{"title":"Coin Dash","genre":"arcade","goal":"reach the coin",'
            '"mechanics":["move"],"win_condition":"touch coin",'
            '"fail_condition":"timeout","entities":[{"name":"Player"},{"name":"Coin"}]}'
        )
        return text, 300, 120
    if "GDScript" in prompt:
        return "extends Node2D\n# ... generated by build model ...\n", 800, 600
    return "A one-screen arcade dash: race to grab the coin before time runs out.", 120, 60


def main() -> None:
    audit = AuditLog()
    kill = KillSwitch(audit)
    gateway = ModelGateway(fake_invoke)
    mcp = GodotMCPClient(MockGodotMCP(seed=1).call_tool)
    skills = GameDevSkills(gateway, mcp)

    verifier = OutcomeVerifier(audit)
    verifier.register("build_passes", lambda d: evaluate_output(d["output"]).verified_value)
    verifier.register("playtest_clears", lambda d: float(d["report_value"]))

    ledger = IncentiveLedger(audit, clawback_window_s=0.0)
    treasury = Treasury(
        TreasuryConfig(per_tx_cap=2.0, rolling_cap=10.0, rolling_window_s=86_400,
                       approval_threshold=2.0,
                       allowed_payees={"model-inference", "compute-cloud"}, dry_run=True),
        audit, kill,
    )
    # Tier 1 earns a little; Tier 2 (playable) earns the bulk.
    harness = IncentiveHarness(verifier, ledger, treasury, BudgetPolicy(1.0, 0.0), audit)

    print("== AgentInko full pipeline ==\n")

    idea = skills.ideate("a relaxing arcade game")
    print("1. IDEATE (Claude):", idea)

    sb = skills.storyboard("JSON game spec: " + idea)  # routes to Claude
    print(f"2. STORYBOARD (Claude): {sb.title} / {sb.genre} — win: {sb.win_condition}")

    build = skills.build_from_storyboard(sb, PROJECT)   # routes to Kimi
    print(f"3. BUILD (Kimi): wrote {build['script_res']}, errors={build['errors']}")

    t1 = harness.submit_outcome("build_passes", {"output": build["output"]}, 1.0)
    print(f"4. TIER 1 verify: {t1.status.value} (+{t1.verified_value})")

    report = PlaytestAgent(mcp).run(PROJECT, sessions=50)
    print(f"5. TIER 2 playtest: completion={report.completion_rate:.0%}, "
          f"softlock={report.softlock_rate:.0%}, value={report.verified_value}")
    print(f"   note: {report.notes[0]}")
    t2 = harness.submit_outcome("playtest_clears", {"report_value": report.verified_value}, 1.0)
    print(f"   TIER 2 verify: {t2.status.value} (+{t2.verified_value})")

    print(f"\n6. Earned budget: ${harness.budget():.2f}")
    print(f"   Model spend so far: ${gateway.total_cost_usd:.4f} {gateway.cost_by_model()}")

    spend = harness.try_spend("model-inference", round(gateway.total_cost_usd, 2),
                              "pay for this build's model inference")
    print(f"   Charge inference cost as a capped spend: {spend.value}")
    print(f"   Net budget after paying costs: ${harness.budget():.2f}")

    print(f"\nAudit log intact: {audit.verify_integrity()} ({len(audit.entries())} entries)")


if __name__ == "__main__":
    main()
