"""
AgentInko dashboard — a zero-dependency local web server (stdlib only).

Runs the real AgentInko pipeline (mock models + mock Godot, so no keys/engine
needed) and serves a funky deep-sea octopus dashboard that visualizes the
incentive tiers, model gateway, treasury guardrails, playtest metrics, and the
tamper-evident audit log.

Run:   python3 dashboard/server.py
Then open http://localhost:8777
"""

from __future__ import annotations

import json
import os
import sys
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse, parse_qs

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "agent_incentive"))

from model_gateway import ModelGateway, ModelSpec
from godot_mcp_client import GodotMCPClient
from mock_godot_mcp import MockGodotMCP
from skills import GameDevSkills
from playtest_agent import PlaytestAgent
from godot_verifier import evaluate_output
from incentive_framework import (
    AuditLog, OutcomeVerifier, IncentiveLedger, Treasury, TreasuryConfig,
    BudgetPolicy, KillSwitch, IncentiveHarness,
)

PORT = 8777


def _fake_invoke(spec: ModelSpec, prompt: str):
    if "JSON game spec" in prompt:
        return ('{"title":"Coin Dash","genre":"arcade","goal":"reach the coin",'
                '"mechanics":["move"],"win_condition":"touch coin",'
                '"fail_condition":"timeout","entities":[{"name":"Player"},{"name":"Coin"}]}',
                300, 120)
    if "GDScript" in prompt:
        return "extends Node2D\n# generated by build model\n", 800, 600
    return "A one-screen arcade dash: grab the coin before time runs out.", 120, 60


# scenario -> mock configuration, so the UI can show the verifier reacting.
SCENARIOS = {
    "healthy":  dict(seed=1),
    "too_hard": dict(seed=1, time_budget=1.0),
    "softlock": dict(seed=3, softlock_zone=(120, 200)),
    "broken":   dict(fault="parse_error"),
}


def build_state(scenario: str = "healthy") -> dict:
    cfg = SCENARIOS.get(scenario, SCENARIOS["healthy"])
    audit = AuditLog()
    kill = KillSwitch(audit)
    gateway = ModelGateway(_fake_invoke)
    mcp = GodotMCPClient(MockGodotMCP(**cfg).call_tool)
    skills = GameDevSkills(gateway, mcp)

    verifier = OutcomeVerifier(audit)
    verifier.register("build_passes", lambda d: evaluate_output(d["output"]).verified_value)
    verifier.register("playtest_clears", lambda d: float(d["report_value"]))
    ledger = IncentiveLedger(audit, clawback_window_s=0.0)
    treasury = Treasury(
        TreasuryConfig(per_tx_cap=2.0, rolling_cap=10.0, rolling_window_s=86_400,
                       approval_threshold=2.0,
                       allowed_payees={"model-inference", "compute-cloud"}, dry_run=True),
        audit, kill,
    )
    harness = IncentiveHarness(verifier, ledger, treasury, BudgetPolicy(1.0, 0.0), audit)

    idea = skills.ideate("a relaxing arcade game")
    sb = skills.storyboard("JSON game spec: " + idea)
    build = skills.build_from_storyboard(sb, "res://inko_coin_dash")
    t1 = harness.submit_outcome("build_passes", {"output": build["output"]}, 1.0)
    report = PlaytestAgent(mcp).run("res://inko_coin_dash", sessions=50)
    t2 = harness.submit_outcome("playtest_clears", {"report_value": report.verified_value}, 1.0)

    inference_cost = round(gateway.total_cost_usd, 4)
    spend = harness.try_spend("model-inference", round(gateway.total_cost_usd, 2),
                              "pay for this build's model inference")

    return {
        "scenario": scenario,
        "agent": "Inko",
        "idea": idea,
        "storyboard": sb.__dict__,
        "build": {"errors": build["errors"], "script": build["script_res"]},
        "tiers": {
            "t1": {"label": "Build integrity", "status": t1.status.value,
                   "value": t1.verified_value, "auto": True},
            "t2": {"label": "Playtest", "status": t2.status.value,
                   "value": t2.verified_value, "auto": True,
                   "completion_rate": report.completion_rate,
                   "softlock_rate": report.softlock_rate,
                   "avg_time_s": report.avg_time_s, "note": report.notes[0]},
            "t3": {"label": "Fun (human signal)", "status": "awaiting",
                   "value": 0.0, "auto": False,
                   "note": "needs real players — never an LLM judge"},
        },
        "gateway": {"total_cost_usd": inference_cost,
                    "by_model": {k: round(v, 4) for k, v in gateway.cost_by_model().items()},
                    "routes": {"design/ideation": "claude", "build/codegen": "kimi"}},
        "treasury": {"budget": round(harness.budget(), 2), "spent": round(harness._spent, 2),
                     "inference_charge": spend.value, "dry_run": True,
                     "per_tx_cap": 2.0, "rolling_cap": 10.0,
                     "allowed_payees": ["model-inference", "compute-cloud"],
                     "killswitch": kill.is_engaged()},
        "audit": [{"event": e["event_type"],
                   "payload": {k: v for k, v in e["payload"].items() if k != "output"}}
                  for e in audit.entries()],
        "audit_intact": audit.verify_integrity(),
    }


class Handler(BaseHTTPRequestHandler):
    def log_message(self, *a):  # quiet
        pass

    def _send(self, code, body, ctype):
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body if isinstance(body, bytes) else body.encode())

    def do_GET(self):
        parsed = urlparse(self.path)
        if parsed.path in ("/", "/index.html"):
            with open(os.path.join(HERE, "index.html"), "rb") as f:
                self._send(200, f.read(), "text/html; charset=utf-8")
        elif parsed.path == "/api/state":
            scenario = (parse_qs(parsed.query).get("scenario", ["healthy"]))[0]
            self._send(200, json.dumps(build_state(scenario)), "application/json")
        else:
            self._send(404, "not found", "text/plain")


def main():
    srv = ThreadingHTTPServer(("127.0.0.1", PORT), Handler)
    print(f"\n  🐙  Inko dashboard swimming at  http://localhost:{PORT}\n")
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        print("\n  Inko retreats to the reef. Bye!\n")


if __name__ == "__main__":
    main()
